#!/bin/bash

# MyApp Version Bumping Script
# Usage:
#   ./scripts/bump_version.sh patch  # 1.0.0 -> 1.0.1
#   ./scripts/bump_version.sh minor  # 1.0.0 -> 1.1.0
#   ./scripts/bump_version.sh major  # 1.0.0 -> 2.0.0

set -e

VERSION_FILE="version.properties"
BUMP_TYPE="${1:-patch}"

if [ ! -f "$VERSION_FILE" ]; then
    echo "❌ Error: $VERSION_FILE not found"
    exit 1
fi

# Read current version
MAJOR=$(grep "VERSION_MAJOR=" $VERSION_FILE | cut -d'=' -f2)
MINOR=$(grep "VERSION_MINOR=" $VERSION_FILE | cut -d'=' -f2)
PATCH=$(grep "VERSION_PATCH=" $VERSION_FILE | cut -d'=' -f2)
CODE=$(grep "VERSION_CODE=" $VERSION_FILE | cut -d'=' -f2)

echo "📦 Current version: $MAJOR.$MINOR.$PATCH (code: $CODE)"

# Bump version based on type
case "$BUMP_TYPE" in
    major)
        MAJOR=$((MAJOR + 1))
        MINOR=0
        PATCH=0
        echo "⬆️  Bumping MAJOR version"
        ;;
    minor)
        MINOR=$((MINOR + 1))
        PATCH=0
        echo "⬆️  Bumping MINOR version"
        ;;
    patch)
        PATCH=$((PATCH + 1))
        echo "⬆️  Bumping PATCH version"
        ;;
    *)
        echo "❌ Error: Invalid bump type '$BUMP_TYPE'"
        echo "Usage: $0 [major|minor|patch]"
        exit 1
        ;;
esac

# Always increment version code
CODE=$((CODE + 1))

NEW_VERSION="$MAJOR.$MINOR.$PATCH"
echo "✅ New version: $NEW_VERSION (code: $CODE)"

# Update version.properties
cat > $VERSION_FILE << EOF
# MyApp Version Management
# This file is auto-generated by version management scripts
# Manual edits will be overwritten

# Semantic versioning: MAJOR.MINOR.PATCH
VERSION_MAJOR=$MAJOR
VERSION_MINOR=$MINOR
VERSION_PATCH=$PATCH

# Version code (increments with each release)
VERSION_CODE=$CODE

# Build metadata (optional)
# BUILD_METADATA=beta
EOF

echo "📝 Updated $VERSION_FILE"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff $VERSION_FILE"
echo "  2. Commit: git add $VERSION_FILE && git commit -m 'chore: Bump version to $NEW_VERSION'"
echo "  3. Tag: git tag v$NEW_VERSION"
echo "  4. Push: git push && git push --tags"
